### ISSUE TITLE
Microwave reciever not working, cant destroy satellites, clone and destroy button texture missing

### ISSUE THREAD

**Issue by BramDeCreep** [zmaster587/AdvancedRocketry#194]
i have found a few bugs first of all i made a microwave reciever and put a satellite in it made from a mricowave transmitter and 3 large solar panels but theres no power coming in the microwave receiver dont know if intensional but the sattelite says the planet name only after being in the sattelite terminal

second issue: whenever i place a programmed sattelite in the sattelite terminal and i click destroy it says unprogrammed but when i re-open the sattelite terminal or take it out it says programmed again but when i click connect it say no link.. and when i program a new sattelite it still counts up like it still exists

third issue: whenever i hover over the destroy sattelite button or write to secondary chip button it shows as a missing texture

**Comment by BramDeCreep** [comment]
by the way how do i toggle hover mode?

**Comment by zmaster587** [comment]
Hover mode can be toggled by hitting sneaking while hitting the toggle jetpack button, however you need to have a hover upgrade installed in the helmet for it to work.

For the microwave satellite, did you put any form of power storage in them (battery?)?

Missing texture was already fixed, and will be in next release.

I'm not sure I understand what you're saying when you say "when i program a new sattelite it still counts up like it still exists".  If you mean the new ID is higher than the previous one, no two satellites can have the same ID, and because it's near impossible to track what items exist in the world with the previous satellite's ID it's not feasible to reuse the id values.

I'll investigate the destroying satellite issue in the morning, right now it's nearly 5AM

**Comment by BramDeCreep** [comment]
Okay i didnt know you need to put battery's in them gonna try iT when pc is done starting up

**Comment by BramDeCreep** [comment]
microwave receiver is still not working i put batterys too this time and it says it has 300 energy storage

**Comment by TheGuyRunningSouth** [comment]
Did you also remember solar panels?

**Comment by zmaster587** [comment]
Did you turn the microwave reciever on in the control block?

**Comment by BramDeCreep** [comment]
Yes and ill try iT later if iT magicly works

**Comment by zmaster587** [comment]
can you send me a copy of the "world/advRocketry/temp.dat"

**Comment by BramDeCreep** [comment]
yes i did, you mean the file or the text inside?

**Comment by BramDeCreep** [comment]
‹       Í×KhAðo»›4ÝÔ¦­¨«(¶Æ–´Ô>h‹ÛZIN>ÓdšŒÝì.3“Ø H/"ˆ'½ôVéÑ«WOUQADñêMD
õâ¥HÙ4ÝÝ€u-XH6óøæ—’‰ C”qDSeÆqé tªmL/R Yt³X˜6‰97@…’§éÐ˜%…	ÂxelXÎ6î¼Ý¢3„§ó˜#ØlMasåË°hHÎ4¸ P½š`7+š”0œ*šs§“Ý´ÁD"10ñú¼dWšmD±É+Umˆ‚½9ŠJ„#N,“EƒÛ ˜ÊQˆeòÄÈŠ1¿6¢ˆ«A!Žƒp¼	[ªìA…¦š31Í•åóD²¢sºlc1Ë@TcB„nSK°q‚™,ÏºiŠ[å¢rRýÏV!Tˆ9]ÎcSR‹’ÅÍC*4ŠõFQÌ½hÐb Æ‡3rDš°3™r÷ Ç[eŠj”®Ù‡ì>Öã¿ïCuB„ŒQ‘±J[©U}“§1%–¨åÚ3"„M‰Û%¬ˆÍZ9ïE@3‘X.4†(Ï«Ð‚J¹ôŸyoC¼`1;)Å&#\V“•ªgþ-âQÏ«€«é»¼ýÌË¥ü3?p|ý³Ëîa@vÚDÑD^tq:'	º¡ø·å•äÛÁ¿¡»úß¾.éç|¿.4j8¨@¦,ãTÂKõ½êM©z¶†jã¥©cÏ_Ù¹@ª5TÛ¾ÞvÙ•²‹8v}‡;½øú}øÚ%_w
¾=÷†WŸ®ÔG(—gg]|'‚Œ^·—Ý;»{Ò®§†]ìè–W«_v(zÛ°›Ò®ÇËnÌÇN•vÉvÚþÓ¥ÅµOõ‘»ÅŽï.»þ í’^v>v/¤]o
»Öò‡ƒ;ÖêÃîÎ“¸Ë‚´ëõ²[ô±ëv
]5ÎèCíÉ%õVß…úøÐÚK]xÂK¼.Ï_‹+¾GÁ×Ìl”Ág®ãgì3ñ<OUÊIS$»:§ÙÌÜÆfç`ÙgÜ”Õ‹Òv9ŒX&¬2­1gÄ±ó'dëlÝ ?N¼‰z¡

**Comment by TheGuyRunningSouth** [comment]
He meant the file.

**Comment by BramDeCreep** [comment]
https://www.dropbox.com/s/wdf1vfse0aouxb9/temp.dat?dl=1

**Comment by zmaster587** [comment]
What version of AR did you create the satellites with?

**Comment by zmaster587** [comment]
Alright I see what happened, there was a bug where in some circumstances the storage in the satellite was not set, should have been fixed https://github.com/zmaster587/AdvancedRocketry/commit/4b25894b51da7e331ca19911c1c9dca4bf419ee2  

Try using this file and see if that fixes it: https://www.dropbox.com/s/b1bvb79cu96s0et/temp.dat?dl=0 I've changed the max storage for the satellite.

**Comment by BramDeCreep** [comment]
Thanks its fixed :D
