### ISSUE TITLE
[1.12.2] Snow invalidated multiblocks

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#938]
Minecraft Version:
- 1.12.2
Forge Version:
- 2517
Advanced Rocketry Version:
- 1.2.5a-13
LibVulpes Version:
- 0.2.6-8

Explain issue in detail:
![image](https://user-images.githubusercontent.com/2363472/32693458-2bccc494-c6f9-11e7-851d-d0ed1b926aae.png)

Seems snowfall will render the structures invalid if it lands on them, in this case an observatory

**Comment by zmaster587** [comment]
Does it happen to all multiblocks or just a few?

**Comment by zmaster587** [comment]
Alright, I fixed the observetory, the rest are fairly square or designed to tolerate blocks in odd places I think.  If any other machines experience this issue, just post and reopen the issue

**Comment by EasterncheesE** [comment]
As far as i remember, i had the issues with space elevator and snow. When it began snowing, the structure became opacue and gave red crosses at snow location.

**Comment by dmodoomsirius** [comment]
Does this issue still happen with the Space Elevator? @EasterncheesE

**Comment by EasterncheesE** [comment]
Sorry, i have forgotten to mention that i tested this for 1.7.10 1.2.5 version 
On this version, the space elevator is being disassembled by snowing.

After installing 1.2.5-47, i see this issue still persist. When snow is lying, but one haven't yet interacted with elevator - all look okay. After a try to interact, it shows the red cross for invalid structure and all become transparent.

**Comment by zmaster587** [comment]
This libvules update should fix the issue with snow or any other replacable block.
